//! @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::{
    DataNotFoundError, FourDayOutlookResponse, InvalidParamsError, RateLimitError,
};
/// <https://api-open.data.gov.sg/v2/real-time/api/four-day-outlook>
///
/// - The forecast is for the next 4 days.
///
/// - Filter for specific date or date-time by providing `date` in query parameter (YYYY-MM-DD or YYYY-MM-DDTHH:MM:SS).
///
/// - example: `?date=2024-07-16` or `?date=2024-07-16T23:59:00`
///
/// - Forecasts are valid for four days, for example, the validity period of the forecast at 1st Jan 1pm is from 1st Jan 1pm to 5th Jan 1pm
///
/// - If `date` is not provided in query parameter, API will return the latest reading
#[derive(Debug, Clone, PartialEq)]
pub struct FourDayOutlookInput {
    /// SGT date for which to retrieve data (YYYY-MM-DD). Omit for latest.
    pub date: Option<satay_runtime::Date>,
    /// Pagination token for subsequent pages (only when date filter is used and more pages exist).
    pub pagination_token: Option<String>,
    /// Optional API key for higher rate limits.
    pub x_api_key: Option<String>,
}
impl FourDayOutlookInput {
    pub fn new() -> Self {
        Self {
            date: None,
            pagination_token: None,
            x_api_key: None,
        }
    }
    pub fn date(mut self, date: satay_runtime::Date) -> Self {
        self.date = Some(date);
        self
    }
    pub fn pagination_token(mut self, pagination_token: impl Into<String>) -> Self {
        self.pagination_token = Some(pagination_token.into());
        self
    }
    pub fn x_api_key(mut self, x_api_key: impl Into<String>) -> Self {
        self.x_api_key = Some(x_api_key.into());
        self
    }
}
impl Default for FourDayOutlookInput {
    fn default() -> Self {
        Self::new()
    }
}
/// <https://api-open.data.gov.sg/v2/real-time/api/four-day-outlook>
///
/// - The forecast is for the next 4 days.
///
/// - Filter for specific date or date-time by providing `date` in query parameter (YYYY-MM-DD or YYYY-MM-DDTHH:MM:SS).
///
/// - example: `?date=2024-07-16` or `?date=2024-07-16T23:59:00`
///
/// - Forecasts are valid for four days, for example, the validity period of the forecast at 1st Jan 1pm is from 1st Jan 1pm to 5th Jan 1pm
///
/// - If `date` is not provided in query parameter, API will return the latest reading
#[derive(Debug, Clone, PartialEq)]
pub enum FourDayOutlookOperationResponse {
    /// 4 Day Weather Forecast
    Ok(FourDayOutlookResponse),
    /// Invalid request (bad date format or pagination token)
    BadRequest(InvalidParamsError),
    /// Weather data not found
    NotFound(DataNotFoundError),
    /// Rate limit exceeded (429). Wait and retry, or use an x-api-key.
    Status429(RateLimitError),
    UnexpectedStatus(http::StatusCode, Vec<u8>),
}
/// <https://api-open.data.gov.sg/v2/real-time/api/four-day-outlook>
///
/// - The forecast is for the next 4 days.
///
/// - Filter for specific date or date-time by providing `date` in query parameter (YYYY-MM-DD or YYYY-MM-DDTHH:MM:SS).
///
/// - example: `?date=2024-07-16` or `?date=2024-07-16T23:59:00`
///
/// - Forecasts are valid for four days, for example, the validity period of the forecast at 1st Jan 1pm is from 1st Jan 1pm to 5th Jan 1pm
///
/// - If `date` is not provided in query parameter, API will return the latest reading
pub fn four_day_outlook_parts(
    input: FourDayOutlookInput,
) -> Result<satay_runtime::RequestParts<()>, satay_runtime::Error> {
    let mut uri = String::with_capacity(17);
    uri.push_str("/four-day-outlook");
    let mut first_query = true;
    if let Some(value) = &input.date {
        satay_runtime::append_query_pair(
            &mut uri,
            &mut first_query,
            "date",
            &satay_runtime::format_date(value),
        );
    }
    if let Some(value) = &input.pagination_token {
        satay_runtime::append_query_pair(
            &mut uri,
            &mut first_query,
            "paginationToken",
            value.as_str(),
        );
    }
    let mut headers = http::HeaderMap::new();
    if let Some(value) = &input.x_api_key {
        satay_runtime::insert_header(&mut headers, "x-api-key", value.as_str())?;
    }
    Ok(satay_runtime::RequestParts {
        method: http::Method::GET,
        uri,
        headers,
        body: (),
    })
}
