//! @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::{
    DataNotFoundError, InvalidParamsError, RateLimitError, TwoHrForecastResponse,
};
use super::parts::{TwoHrForecastInput, TwoHrForecastOperationResponse, two_hr_forecast_parts};
/// <https://api-open.data.gov.sg/v2/real-time/api/two-hr-forecast>
///
/// - Forecasts are given for multiple areas in Singapore
///
/// - Filter for specific date or date-time by providing `date` in query parameter (YYYY-MM-DD or YYYY-MM-DDTHH:MM:SS).
///
/// - example: `?date=2024-07-16` or `?date=2024-07-16T23:59:00`
///
/// - Forecasts are valid for two hours, for example, the validity period of the forecast at 1pm is 1pm to 3pm
///
/// - If `date` is not provided in query parameter, API will return the latest reading
pub fn encode_two_hr_forecast(
    input: TwoHrForecastInput,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = two_hr_forecast_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
pub fn decode_two_hr_forecast_response<B: AsRef<[u8]>>(
    response: satay_runtime::ResponseParts<B>,
) -> Result<TwoHrForecastOperationResponse, satay_runtime::Error> {
    let status = response.status;
    match status.as_u16() {
        200 => {
            let body = response.body;
            let value = satay_runtime::from_json_slice::<TwoHrForecastResponse>(body.as_ref())?;
            Ok(TwoHrForecastOperationResponse::Ok(value))
        }
        400 => {
            let body = response.body;
            let value = satay_runtime::from_json_slice::<InvalidParamsError>(body.as_ref())?;
            Ok(TwoHrForecastOperationResponse::BadRequest(value))
        }
        404 => {
            let body = response.body;
            let value = satay_runtime::from_json_slice::<DataNotFoundError>(body.as_ref())?;
            Ok(TwoHrForecastOperationResponse::NotFound(value))
        }
        429 => {
            let body = response.body;
            let value = satay_runtime::from_json_slice::<RateLimitError>(body.as_ref())?;
            Ok(TwoHrForecastOperationResponse::Status429(value))
        }
        _ => {
            let body = response.body;
            Ok(TwoHrForecastOperationResponse::UnexpectedStatus(
                status,
                body.as_ref().to_vec(),
            ))
        }
    }
}
