// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::{
    AirTemperatureResponse, DataNotFoundError, InvalidParamsError, RateLimitError,
};
use super::parts::{AirTemperatureInput, AirTemperatureOperationResponse, air_temperature_parts};
use serde::de;
/// <https://api-open.data.gov.sg/v2/real-time/api/air-temperature>
///
/// - Filter for a specific date by providing `date` in query parameter (YYYY-MM-DD).
///
/// - example: `?date=2024-07-16`
///
/// - If `date` is not provided in query parameter, API will return the latest reading
///
/// - Unit of measure for readings is `°C`
pub fn encode_air_temperature<
    S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned,
>(
    input: AirTemperatureInput<S>,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = air_temperature_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
pub fn decode_air_temperature_response<
    S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned,
>(
    response: satay_runtime::ResponseParts<&[u8]>,
) -> Result<AirTemperatureOperationResponse<S>, satay_runtime::Error> {
    let status = response.status;
    match status.as_u16() {
        200 => {
            let body = response.body;
            let value = satay_runtime::from_json_slice::<AirTemperatureResponse<S>>(body)?;
            Ok(AirTemperatureOperationResponse::<S>::Ok(value))
        }
        400 => {
            let body = response.body;
            let value = satay_runtime::from_json_slice::<InvalidParamsError<S>>(body)?;
            Ok(AirTemperatureOperationResponse::<S>::BadRequest(value))
        }
        404 => {
            let body = response.body;
            let value = satay_runtime::from_json_slice::<DataNotFoundError<S>>(body)?;
            Ok(AirTemperatureOperationResponse::<S>::NotFound(value))
        }
        429 => {
            let body = response.body;
            let value = satay_runtime::from_json_slice::<RateLimitError<S>>(body)?;
            Ok(AirTemperatureOperationResponse::<S>::Status429(value))
        }
        _ => {
            let body = response.body;
            Ok(AirTemperatureOperationResponse::<S>::UnexpectedStatus(
                status,
                body.to_vec(),
            ))
        }
    }
}
