//! @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::{
    DataNotFoundError, InvalidParamsError, RateLimitError, WindSpeedResponse,
};
use super::parts::{WindSpeedInput, WindSpeedOperationResponse, wind_speed_parts};
/// <https://api-open.data.gov.sg/v2/real-time/api/wind-speed>
///
/// - Filter for a specific date by providing `date` in query parameter (YYYY-MM-DD).
///
/// - example: `?date=2024-07-16`
///
/// - If `date` is not provided in query parameter, API will return the latest reading
///
/// - Unit of measure for readings is `Knots`
pub fn encode_wind_speed(
    input: WindSpeedInput,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = wind_speed_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
pub fn decode_wind_speed_response<B: AsRef<[u8]>>(
    response: satay_runtime::ResponseParts<B>,
) -> Result<WindSpeedOperationResponse, satay_runtime::Error> {
    let status = response.status;
    match status.as_u16() {
        200 => {
            let body = response.body;
            let value = satay_runtime::from_json_slice::<WindSpeedResponse>(body.as_ref())?;
            Ok(WindSpeedOperationResponse::Ok(value))
        }
        400 => {
            let body = response.body;
            let value = satay_runtime::from_json_slice::<InvalidParamsError>(body.as_ref())?;
            Ok(WindSpeedOperationResponse::BadRequest(value))
        }
        404 => {
            let body = response.body;
            let value = satay_runtime::from_json_slice::<DataNotFoundError>(body.as_ref())?;
            Ok(WindSpeedOperationResponse::NotFound(value))
        }
        429 => {
            let body = response.body;
            let value = satay_runtime::from_json_slice::<RateLimitError>(body.as_ref())?;
            Ok(WindSpeedOperationResponse::Status429(value))
        }
        _ => {
            let body = response.body;
            Ok(WindSpeedOperationResponse::UnexpectedStatus(
                status,
                body.as_ref().to_vec(),
            ))
        }
    }
}
