// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::air_temperature::{air_temperature_parts, decode_air_temperature_response};
use super::four_day_outlook::{decode_four_day_outlook_response, four_day_outlook_parts};
use super::pm25::{decode_pm25_response, pm25_parts};
use super::psi::{decode_psi_response, psi_parts};
use super::rainfall::{decode_rainfall_response, rainfall_parts};
use super::relative_humidity::{decode_relative_humidity_response, relative_humidity_parts};
use super::twenty_four_hr_forecast::{
    decode_twenty_four_hr_forecast_response, twenty_four_hr_forecast_parts,
};
use super::two_hr_forecast::{decode_two_hr_forecast_response, two_hr_forecast_parts};
use super::uv::{decode_uv_response, uv_parts};
use super::weather_sub_api::{decode_weather_sub_api_response, weather_sub_api_parts};
use super::wind_direction::{decode_wind_direction_response, wind_direction_parts};
use super::wind_speed::{decode_wind_speed_response, wind_speed_parts};
use super::{
    AirTemperatureInput, AirTemperatureOperationResponse, FourDayOutlookInput,
    FourDayOutlookOperationResponse, NeaWeatherSubApi, Pm25Input, Pm25OperationResponse, PsiInput,
    PsiOperationResponse, RainfallInput, RainfallOperationResponse, RelativeHumidityInput,
    RelativeHumidityOperationResponse, TwentyFourHrForecastInput,
    TwentyFourHrForecastOperationResponse, TwoHrForecastInput, TwoHrForecastOperationResponse,
    UvInput, UvOperationResponse, WeatherSubApiInput, WeatherSubApiOperationResponse,
    WindDirectionInput, WindDirectionOperationResponse, WindSpeedInput, WindSpeedOperationResponse,
};
use crate::air_quality;
use crate::environment;
use crate::weather_forecast;
use crate::weather_readings;
use serde::de;
use std::marker;
#[derive(Debug, Clone)]
pub struct Api<S: satay_runtime::StringStorage = String> {
    base_url: String,
    x_api_key: Option<String>,
    __satay_storage: marker::PhantomData<fn() -> S>,
}
impl<S: satay_runtime::StringStorage> Default for Api<S> {
    fn default() -> Self {
        Api::new().string_storage()
    }
}
impl<S: satay_runtime::StringStorage> Api<S> {
    pub fn base_url(mut self, base_url: impl Into<String>) -> Self {
        self.base_url = base_url.into();
        self
    }
    pub fn x_api_key(mut self, value: impl Into<String>) -> Self {
        self.x_api_key = Some(value.into());
        self
    }
    /// Access operations tagged `Air Quality`.
    pub fn air_quality(&self) -> air_quality::Api<'_, S> {
        air_quality::Api { api: self }
    }
    /// Access operations tagged `Weather Readings`.
    pub fn weather_readings(&self) -> weather_readings::Api<'_, S> {
        weather_readings::Api { api: self }
    }
    /// Access operations tagged `Weather Forecast`.
    pub fn weather_forecast(&self) -> weather_forecast::Api<'_, S> {
        weather_forecast::Api { api: self }
    }
    /// Access operations tagged `Environment`.
    pub fn environment(&self) -> environment::Api<'_, S> {
        environment::Api { api: self }
    }
    fn apply<B>(
        &self,
        parts: &mut satay_runtime::RequestParts<B>,
    ) -> Result<(), satay_runtime::Error> {
        if let Some(value) = &self.x_api_key {
            satay_runtime::insert_header(&mut parts.headers, "x-api-key", value)?;
        }
        if self.base_url.is_empty() {
            return Ok(());
        }
        let path_and_query = parts.uri.as_str();
        let base_url = self.base_url.trim_end_matches('/');
        let separator = if path_and_query.starts_with('/') {
            ""
        } else {
            "/"
        };
        parts.uri = format!("{base_url}{separator}{path_and_query}");
        Ok(())
    }
    /// Selects dynamic string storage for generated models and actions.
    pub fn string_storage<T: satay_runtime::StringStorage>(self) -> Api<T> {
        Api {
            base_url: self.base_url,
            x_api_key: self.x_api_key,
            __satay_storage: marker::PhantomData,
        }
    }
}
/// <https://api-open.data.gov.sg/v2/real-time/api/psi>
///
/// - Readings are provided for each major region in Singapore
///
/// - Filter for a specific date by providing `date` in query parameter (YYYY-MM-DD).
///
/// - example: `?date=2024-07-16`
///
/// - If `date` is not provided in query parameter, API will return the latest reading
///
/// - The `region_metadata` field in the response provides longitude/latitude information for the regions. You can use that to place the readings on a map.
///
/// - Unit of measure for readings is `PSI Value`
///
/// Use the chainable methods to configure optional request settings, then call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct PsiAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: PsiInput<S>,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    PsiAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: PsiInput::<S>::new(),
        }
    }
    /// SGT date for which to retrieve data (YYYY-MM-DD). Omit for latest.
    #[must_use = "builder methods return the configured action"]
    pub fn date(mut self, date: satay_runtime::Date) -> Self {
        self.input = self.input.date(date);
        self
    }
    /// Pagination token for subsequent pages (only when date filter is used and more pages exist).
    #[must_use = "builder methods return the configured action"]
    pub fn pagination_token(mut self, pagination_token: impl Into<S>) -> Self {
        self.input = self.input.pagination_token(pagination_token);
        self
    }
    /// Optional API key for higher rate limits.
    #[must_use = "builder methods return the configured action"]
    pub fn x_api_key(mut self, x_api_key: impl Into<S>) -> Self {
        self.input = self.input.x_api_key(x_api_key);
        self
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = psi_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<PsiOperationResponse<S>, satay_runtime::Error> {
        decode_psi_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for PsiAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = PsiOperationResponse<S>;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for PsiAction<'_, S>
{
    type OwnedResponse = PsiOperationResponse<S>;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// <https://api-open.data.gov.sg/v2/real-time/api/pm25>
///
/// - Readings are provided for each major region in Singapore
///
/// - Filter for a specific date by providing `date` in query parameter (YYYY-MM-DD).
///
/// - example: `?date=2024-07-16`
///
/// - If `date` is not provided in query parameter, API will return the latest reading
///
/// - The `region_metadata` field in the response provides longitude/latitude information for the regions. You can use that to place the readings on a map.
///
/// - Unit of measure for readings is `µg/m3`.
///
/// Use the chainable methods to configure optional request settings, then call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct Pm25Action<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: Pm25Input<S>,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    Pm25Action<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: Pm25Input::<S>::new(),
        }
    }
    /// SGT date for which to retrieve data (YYYY-MM-DD). Omit for latest.
    #[must_use = "builder methods return the configured action"]
    pub fn date(mut self, date: satay_runtime::Date) -> Self {
        self.input = self.input.date(date);
        self
    }
    /// Pagination token for subsequent pages (only when date filter is used and more pages exist).
    #[must_use = "builder methods return the configured action"]
    pub fn pagination_token(mut self, pagination_token: impl Into<S>) -> Self {
        self.input = self.input.pagination_token(pagination_token);
        self
    }
    /// Optional API key for higher rate limits.
    #[must_use = "builder methods return the configured action"]
    pub fn x_api_key(mut self, x_api_key: impl Into<S>) -> Self {
        self.input = self.input.x_api_key(x_api_key);
        self
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = pm25_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Pm25OperationResponse<S>, satay_runtime::Error> {
        decode_pm25_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for Pm25Action<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = Pm25OperationResponse<S>;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for Pm25Action<'_, S>
{
    type OwnedResponse = Pm25OperationResponse<S>;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// <https://api-open.data.gov.sg/v2/real-time/api/air-temperature>
///
/// - Filter for a specific date by providing `date` in query parameter (YYYY-MM-DD).
///
/// - example: `?date=2024-07-16`
///
/// - If `date` is not provided in query parameter, API will return the latest reading
///
/// - Unit of measure for readings is `°C`
///
/// Use the chainable methods to configure optional request settings, then call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct AirTemperatureAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: AirTemperatureInput<S>,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    AirTemperatureAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: AirTemperatureInput::<S>::new(),
        }
    }
    /// SGT date for which to retrieve data (YYYY-MM-DD). Omit for latest.
    #[must_use = "builder methods return the configured action"]
    pub fn date(mut self, date: satay_runtime::Date) -> Self {
        self.input = self.input.date(date);
        self
    }
    /// Pagination token for subsequent pages (only when date filter is used and more pages exist).
    #[must_use = "builder methods return the configured action"]
    pub fn pagination_token(mut self, pagination_token: impl Into<S>) -> Self {
        self.input = self.input.pagination_token(pagination_token);
        self
    }
    /// Optional API key for higher rate limits.
    #[must_use = "builder methods return the configured action"]
    pub fn x_api_key(mut self, x_api_key: impl Into<S>) -> Self {
        self.input = self.input.x_api_key(x_api_key);
        self
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = air_temperature_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<AirTemperatureOperationResponse<S>, satay_runtime::Error> {
        decode_air_temperature_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for AirTemperatureAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = AirTemperatureOperationResponse<S>;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for AirTemperatureAction<'_, S>
{
    type OwnedResponse = AirTemperatureOperationResponse<S>;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// <https://api-open.data.gov.sg/v2/real-time/api/relative-humidity>
///
/// - Filter for a specific date by providing `date` in query parameter (YYYY-MM-DD).
///
/// - example: `?date=2024-07-16`
///
/// - If `date` is not provided in query parameter, API will return the latest reading
///
/// - Unit of measure for readings is `%`
///
/// Use the chainable methods to configure optional request settings, then call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct RelativeHumidityAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: RelativeHumidityInput<S>,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    RelativeHumidityAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: RelativeHumidityInput::<S>::new(),
        }
    }
    /// SGT date for which to retrieve data (YYYY-MM-DD). Omit for latest.
    #[must_use = "builder methods return the configured action"]
    pub fn date(mut self, date: satay_runtime::Date) -> Self {
        self.input = self.input.date(date);
        self
    }
    /// Pagination token for subsequent pages (only when date filter is used and more pages exist).
    #[must_use = "builder methods return the configured action"]
    pub fn pagination_token(mut self, pagination_token: impl Into<S>) -> Self {
        self.input = self.input.pagination_token(pagination_token);
        self
    }
    /// Optional API key for higher rate limits.
    #[must_use = "builder methods return the configured action"]
    pub fn x_api_key(mut self, x_api_key: impl Into<S>) -> Self {
        self.input = self.input.x_api_key(x_api_key);
        self
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = relative_humidity_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<RelativeHumidityOperationResponse<S>, satay_runtime::Error> {
        decode_relative_humidity_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for RelativeHumidityAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = RelativeHumidityOperationResponse<S>;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for RelativeHumidityAction<'_, S>
{
    type OwnedResponse = RelativeHumidityOperationResponse<S>;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// <https://api-open.data.gov.sg/v2/real-time/api/wind-speed>
///
/// - Filter for a specific date by providing `date` in query parameter (YYYY-MM-DD).
///
/// - example: `?date=2024-07-16`
///
/// - If `date` is not provided in query parameter, API will return the latest reading
///
/// - Unit of measure for readings is `Knots`
///
/// Use the chainable methods to configure optional request settings, then call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct WindSpeedAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: WindSpeedInput<S>,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    WindSpeedAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: WindSpeedInput::<S>::new(),
        }
    }
    /// SGT date for which to retrieve data (YYYY-MM-DD). Omit for latest.
    #[must_use = "builder methods return the configured action"]
    pub fn date(mut self, date: satay_runtime::Date) -> Self {
        self.input = self.input.date(date);
        self
    }
    /// Pagination token for subsequent pages (only when date filter is used and more pages exist).
    #[must_use = "builder methods return the configured action"]
    pub fn pagination_token(mut self, pagination_token: impl Into<S>) -> Self {
        self.input = self.input.pagination_token(pagination_token);
        self
    }
    /// Optional API key for higher rate limits.
    #[must_use = "builder methods return the configured action"]
    pub fn x_api_key(mut self, x_api_key: impl Into<S>) -> Self {
        self.input = self.input.x_api_key(x_api_key);
        self
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = wind_speed_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<WindSpeedOperationResponse<S>, satay_runtime::Error> {
        decode_wind_speed_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for WindSpeedAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = WindSpeedOperationResponse<S>;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for WindSpeedAction<'_, S>
{
    type OwnedResponse = WindSpeedOperationResponse<S>;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// <https://api-open.data.gov.sg/v2/real-time/api/wind-direction>
///
/// - Filter for a specific date by providing `date` in query parameter (YYYY-MM-DD).
///
/// - example: `?date=2024-07-16`
///
/// - If `date` is not provided in query parameter, API will return the latest reading
///
/// - Unit of measure for readings is `°`
///
/// Use the chainable methods to configure optional request settings, then call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct WindDirectionAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: WindDirectionInput<S>,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    WindDirectionAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: WindDirectionInput::<S>::new(),
        }
    }
    /// SGT date for which to retrieve data (YYYY-MM-DD). Omit for latest.
    #[must_use = "builder methods return the configured action"]
    pub fn date(mut self, date: satay_runtime::Date) -> Self {
        self.input = self.input.date(date);
        self
    }
    /// Pagination token for subsequent pages (only when date filter is used and more pages exist).
    #[must_use = "builder methods return the configured action"]
    pub fn pagination_token(mut self, pagination_token: impl Into<S>) -> Self {
        self.input = self.input.pagination_token(pagination_token);
        self
    }
    /// Optional API key for higher rate limits.
    #[must_use = "builder methods return the configured action"]
    pub fn x_api_key(mut self, x_api_key: impl Into<S>) -> Self {
        self.input = self.input.x_api_key(x_api_key);
        self
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = wind_direction_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<WindDirectionOperationResponse<S>, satay_runtime::Error> {
        decode_wind_direction_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for WindDirectionAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = WindDirectionOperationResponse<S>;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for WindDirectionAction<'_, S>
{
    type OwnedResponse = WindDirectionOperationResponse<S>;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// <https://api-open.data.gov.sg/v2/real-time/api/rainfall>
///
/// - Filter for a specific date by providing `date` in query parameter (YYYY-MM-DD).
///
/// - example: `?date=2024-07-16`
///
/// - If `date` is not provided in query parameter, API will return the latest reading
///
/// - Unit of measure for readings is `mm`
///
/// Use the chainable methods to configure optional request settings, then call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct RainfallAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: RainfallInput<S>,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    RainfallAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: RainfallInput::<S>::new(),
        }
    }
    /// SGT date for which to retrieve data (YYYY-MM-DD). Omit for latest.
    #[must_use = "builder methods return the configured action"]
    pub fn date(mut self, date: satay_runtime::Date) -> Self {
        self.input = self.input.date(date);
        self
    }
    /// Pagination token for subsequent pages (only when date filter is used and more pages exist).
    #[must_use = "builder methods return the configured action"]
    pub fn pagination_token(mut self, pagination_token: impl Into<S>) -> Self {
        self.input = self.input.pagination_token(pagination_token);
        self
    }
    /// Optional API key for higher rate limits.
    #[must_use = "builder methods return the configured action"]
    pub fn x_api_key(mut self, x_api_key: impl Into<S>) -> Self {
        self.input = self.input.x_api_key(x_api_key);
        self
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = rainfall_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<RainfallOperationResponse<S>, satay_runtime::Error> {
        decode_rainfall_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for RainfallAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = RainfallOperationResponse<S>;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for RainfallAction<'_, S>
{
    type OwnedResponse = RainfallOperationResponse<S>;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// <https://api-open.data.gov.sg/v2/real-time/api/two-hr-forecast>
///
/// - Forecasts are given for multiple areas in Singapore
///
/// - Filter for specific date or date-time by providing `date` in query parameter (YYYY-MM-DD or YYYY-MM-DDTHH:MM:SS).
///
/// - example: `?date=2024-07-16` or `?date=2024-07-16T23:59:00`
///
/// - Forecasts are valid for two hours, for example, the validity period of the forecast at 1pm is 1pm to 3pm
///
/// - If `date` is not provided in query parameter, API will return the latest reading
///
/// Use the chainable methods to configure optional request settings, then call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct TwoHrForecastAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: TwoHrForecastInput<S>,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    TwoHrForecastAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: TwoHrForecastInput::<S>::new(),
        }
    }
    /// SGT date for which to retrieve data (YYYY-MM-DD). Omit for latest.
    #[must_use = "builder methods return the configured action"]
    pub fn date(mut self, date: satay_runtime::Date) -> Self {
        self.input = self.input.date(date);
        self
    }
    /// Pagination token for subsequent pages (only when date filter is used and more pages exist).
    #[must_use = "builder methods return the configured action"]
    pub fn pagination_token(mut self, pagination_token: impl Into<S>) -> Self {
        self.input = self.input.pagination_token(pagination_token);
        self
    }
    /// Optional API key for higher rate limits.
    #[must_use = "builder methods return the configured action"]
    pub fn x_api_key(mut self, x_api_key: impl Into<S>) -> Self {
        self.input = self.input.x_api_key(x_api_key);
        self
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = two_hr_forecast_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<TwoHrForecastOperationResponse<S>, satay_runtime::Error> {
        decode_two_hr_forecast_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for TwoHrForecastAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = TwoHrForecastOperationResponse<S>;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for TwoHrForecastAction<'_, S>
{
    type OwnedResponse = TwoHrForecastOperationResponse<S>;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// <https://api-open.data.gov.sg/v2/real-time/api/twenty-four-hr-forecast>
///
/// - Updated multiple times throughout the day
///
/// - Filter for specific date or date-time by providing `date` in query parameter (YYYY-MM-DD or YYYY-MM-DDTHH:MM:SS).
///
/// - example: `?date=2024-07-16` or `?date=2024-07-16T23:59:00`
///
/// - Forecasts are valid for twenty four hours, for example, the validity period of the forecast at 1st Jan 1pm is from 1st Jan 1pm to 2nd Jan 1pm
///
/// - If `date` is not provided in query parameter, API will return the latest reading
///
/// Use the chainable methods to configure optional request settings, then call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct TwentyFourHrForecastAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: TwentyFourHrForecastInput<S>,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    TwentyFourHrForecastAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: TwentyFourHrForecastInput::<S>::new(),
        }
    }
    /// SGT date for which to retrieve data (YYYY-MM-DD). Omit for latest.
    #[must_use = "builder methods return the configured action"]
    pub fn date(mut self, date: satay_runtime::Date) -> Self {
        self.input = self.input.date(date);
        self
    }
    /// Pagination token for subsequent pages (only when date filter is used and more pages exist).
    #[must_use = "builder methods return the configured action"]
    pub fn pagination_token(mut self, pagination_token: impl Into<S>) -> Self {
        self.input = self.input.pagination_token(pagination_token);
        self
    }
    /// Optional API key for higher rate limits.
    #[must_use = "builder methods return the configured action"]
    pub fn x_api_key(mut self, x_api_key: impl Into<S>) -> Self {
        self.input = self.input.x_api_key(x_api_key);
        self
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = twenty_four_hr_forecast_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<TwentyFourHrForecastOperationResponse<S>, satay_runtime::Error> {
        decode_twenty_four_hr_forecast_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for TwentyFourHrForecastAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = TwentyFourHrForecastOperationResponse<S>;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for TwentyFourHrForecastAction<'_, S>
{
    type OwnedResponse = TwentyFourHrForecastOperationResponse<S>;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// <https://api-open.data.gov.sg/v2/real-time/api/four-day-outlook>
///
/// - The forecast is for the next 4 days.
///
/// - Filter for specific date or date-time by providing `date` in query parameter (YYYY-MM-DD or YYYY-MM-DDTHH:MM:SS).
///
/// - example: `?date=2024-07-16` or `?date=2024-07-16T23:59:00`
///
/// - Forecasts are valid for four days, for example, the validity period of the forecast at 1st Jan 1pm is from 1st Jan 1pm to 5th Jan 1pm
///
/// - If `date` is not provided in query parameter, API will return the latest reading
///
/// Use the chainable methods to configure optional request settings, then call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct FourDayOutlookAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: FourDayOutlookInput<S>,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    FourDayOutlookAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: FourDayOutlookInput::<S>::new(),
        }
    }
    /// SGT date for which to retrieve data (YYYY-MM-DD). Omit for latest.
    #[must_use = "builder methods return the configured action"]
    pub fn date(mut self, date: satay_runtime::Date) -> Self {
        self.input = self.input.date(date);
        self
    }
    /// Pagination token for subsequent pages (only when date filter is used and more pages exist).
    #[must_use = "builder methods return the configured action"]
    pub fn pagination_token(mut self, pagination_token: impl Into<S>) -> Self {
        self.input = self.input.pagination_token(pagination_token);
        self
    }
    /// Optional API key for higher rate limits.
    #[must_use = "builder methods return the configured action"]
    pub fn x_api_key(mut self, x_api_key: impl Into<S>) -> Self {
        self.input = self.input.x_api_key(x_api_key);
        self
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = four_day_outlook_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<FourDayOutlookOperationResponse<S>, satay_runtime::Error> {
        decode_four_day_outlook_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for FourDayOutlookAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = FourDayOutlookOperationResponse<S>;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for FourDayOutlookAction<'_, S>
{
    type OwnedResponse = FourDayOutlookOperationResponse<S>;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// <https://api-open.data.gov.sg/v2/real-time/api/uv>
///
/// - Updated between 7 AM and 7 PM everyday
///
/// - The UV index value is averaged over the preceding hour
///
/// - Filter for a specific date by providing `date` in query parameter (YYYY-MM-DD).
///
/// - example: `?date=2024-07-16`
///
/// - If `date` is not provided in query parameter, API will return the latest reading
///
/// - Unit of measure for readings is `Ultraviolet Index`
///
/// Use the chainable methods to configure optional request settings, then call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct UvAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: UvInput<S>,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    UvAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: UvInput::<S>::new(),
        }
    }
    /// SGT date for which to retrieve data (YYYY-MM-DD). Omit for latest.
    #[must_use = "builder methods return the configured action"]
    pub fn date(mut self, date: satay_runtime::Date) -> Self {
        self.input = self.input.date(date);
        self
    }
    /// Pagination token for subsequent pages (only when date filter is used and more pages exist).
    #[must_use = "builder methods return the configured action"]
    pub fn pagination_token(mut self, pagination_token: impl Into<S>) -> Self {
        self.input = self.input.pagination_token(pagination_token);
        self
    }
    /// Optional API key for higher rate limits.
    #[must_use = "builder methods return the configured action"]
    pub fn x_api_key(mut self, x_api_key: impl Into<S>) -> Self {
        self.input = self.input.x_api_key(x_api_key);
        self
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = uv_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<UvOperationResponse<S>, satay_runtime::Error> {
        decode_uv_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for UvAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = UvOperationResponse<S>;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for UvAction<'_, S>
{
    type OwnedResponse = UvOperationResponse<S>;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// Unified weather sub-API endpoint.
///
/// - `?api=lightning` — Cloud-to-ground and cloud-to-cloud lightning strikes. Updated every ~2–3 minutes.
///
/// - `?api=wbgt` — Wet Bulb Globe Temperature heat stress readings. Updated every 15 minutes.
///
/// <https://api-open.data.gov.sg/v2/real-time/api/weather?api=lightning>
///
/// - Updated multiple times throughout the day
///
/// - Filter for a specific date by providing `date` in query parameter (YYYY-MM-DD).
///
/// - example: `?date=2025-01-16`
///
/// - If `date` is not provided in query parameter, API will return the latest lightning observation
///
/// Use the chainable methods to configure optional request settings, then call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct WeatherSubApiAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: WeatherSubApiInput<S>,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    WeatherSubApiAction<'a, S>
{
    pub(crate) fn new(api_2: &'a Api<S>, api: NeaWeatherSubApi) -> Self {
        Self {
            api: api_2,
            input: WeatherSubApiInput::<S>::new(api),
        }
    }
    /// SGT date for which to retrieve data (YYYY-MM-DD). Omit for latest.
    #[must_use = "builder methods return the configured action"]
    pub fn date(mut self, date: satay_runtime::Date) -> Self {
        self.input = self.input.date(date);
        self
    }
    /// Pagination token for subsequent pages (only when date filter is used and more pages exist).
    #[must_use = "builder methods return the configured action"]
    pub fn pagination_token(mut self, pagination_token: impl Into<S>) -> Self {
        self.input = self.input.pagination_token(pagination_token);
        self
    }
    /// Optional API key for higher rate limits.
    #[must_use = "builder methods return the configured action"]
    pub fn x_api_key(mut self, x_api_key: impl Into<S>) -> Self {
        self.input = self.input.x_api_key(x_api_key);
        self
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = weather_sub_api_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<WeatherSubApiOperationResponse<S>, satay_runtime::Error> {
        decode_weather_sub_api_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for WeatherSubApiAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = WeatherSubApiOperationResponse<S>;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for WeatherSubApiAction<'_, S>
{
    type OwnedResponse = WeatherSubApiOperationResponse<S>;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl Api<String> {
    pub fn new() -> Self {
        Self {
            base_url: super::SERVER_URL.to_owned(),
            x_api_key: None,
            __satay_storage: marker::PhantomData,
        }
    }
}
