//! @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

pub const SERVER_URL: &str = "https://api-open.data.gov.sg/v2/real-time/api";
pub mod types;
pub use types::*;
#[cfg(feature = "json")]
mod api;
#[cfg(feature = "json")]
pub use api::*;
pub mod psi;
pub use psi::*;
pub mod pm25;
pub use pm25::*;
pub mod air_temperature;
pub use air_temperature::*;
pub mod relative_humidity;
pub use relative_humidity::*;
pub mod wind_speed;
pub use wind_speed::*;
pub mod wind_direction;
pub use wind_direction::*;
pub mod rainfall;
pub use rainfall::*;
pub mod two_hr_forecast;
pub use two_hr_forecast::*;
pub mod twenty_four_hr_forecast;
pub use twenty_four_hr_forecast::*;
pub mod four_day_outlook;
pub use four_day_outlook::*;
pub mod uv;
pub use uv::*;
pub mod weather_sub_api;
pub use weather_sub_api::*;
